# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PhotoShare' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PhotoShare
pod 'NCMB', :git => 'https://github.com/NIFTYCloud-mbaas/ncmb_ios.git'

end
